Repository fvtt-fria-ligan/forbidden-lands-foundry-vtt, pull requests merged in 2021-09, with the labels that each got.

#150 feat: Improving styling of visual components
  src/lang/pt-br.json
  src/module/sheets/actor/character.js
  src/styles/components/_dialog.scss
  src/styles/components/_util-classes.scss
  src/styles/system/_foundry-overrides.scss
  src/templates/character.hbs
  src/templates/dice/dialog.hbs
  src/templates/dice/spell-dialog.hbs
  src/templates/monster.hbs
  static/assets/journal-art/attack-border.webp
  static/assets/journal-art/endstop.webp
  static/assets/journal-art/pentagram-border.webp
Labels: feature, qol

#153 ✨ Monsters have normal Talents and Spells
  src/lang/cs.json
  src/lang/de.json
  src/lang/en.json
  src/lang/es.json
  src/lang/fr.json
  src/lang/pt-br.json
  src/lang/sv.json
  src/lang/zh-TW.json
  src/module/components/roll-engine/engine.js
  src/module/hooks/handlebars.js
  src/module/hooks/migration.js
  src/module/hooks/sheets.js
  src/module/sheets/actor/actor.js
  src/module/sheets/actor/character.js
  src/module/sheets/actor/monster.js
  src/module/sheets/item/item.js
  src/module/sheets/item/monster-talent.js
  src/module/system/config.js
  src/styles/sheets/tab/_monster-combat.scss
  src/styles/system/_foundry-overrides.scss
  src/templates/chat/consumable.hbs
  src/templates/chat/item.hbs
  src/templates/monster-talent.hbs
  src/templates/tab/combat-monster.hbs
  src/templates/talent.hbs
  static/template.json
Labels: feature

#157 🐛 Damage, Critical Injuries, Encumbrance and Artifacts
  src/module/components/roll-engine/engine.js
  src/module/sheets/actor/character.js
  src/module/system/config.js
  src/module/system/entities.js
  src/templates/chat/item.hbs
  src/templates/dice/dialog.hbs
Labels: fix

#156 Change Pride button to 'button' type
  src/templates/tab/bio.hbs
Labels: fix

#159 Updated Localization files
  src/lang/pt-br.json
  src/lang/ru.json
Labels: feature
