Repository fvtt-fria-ligan/forbidden-lands-foundry-vtt, pull requests merged in 2021-02, with the labels that each got.

#12 Redesign parts of the weapon sheet ⚔📜
  README.md
  lang/en.json
  lang/fr.json
  lang/sv.json
  model/weapon.html
  model/weapon/tab/weapon_artifact.html
  model/weapon/tab/weapon_main.html
  model/weapon/tab/weapon_supply.html
  script/hooks/handlebars.js
  script/sheet/weapon.js
  style/item.css
Labels: enhancement

#30 Artifact-Armors-and-Gear
  chat/item.html
  lang/cs.json
  lang/de.json
  lang/en.json
  lang/fr.json
  lang/pt-br.json
  lang/sv.json
  model/armor.html
  model/character.html
  model/critical-injury.html
  model/gear.html
  model/hireling.html
  model/raw-material.html
  model/spell.html
  model/tab/gear-character.html
  model/tab/gear/armor-main.html
  model/tab/gear/gear-artifact.html
  model/tab/gear/gear-main.html
  model/tab/gear/gear-supply.html
  model/tab/gear/weapon-main.html
  model/tab/hireling-stronghold.html
  model/talent.html
  model/weapon.html
  script/dialog/roll-dialog.js
  script/hooks/handlebars.js
  script/sheet/armor.js
  script/sheet/gear.js
  script/sheet/item.js
  script/sheet/weapon.js
  style/item.css
  style/tab/gear.css
  template.json
Labels: enhancement, missing feature

#42 add spanish lang
  lang/es.json
  system.json
Labels: localization

#45 Special Encumbrance Values
  lang/en.json
  model/tab/gear/gear-main.html
  script/hooks/handlebars.js
  script/sheet/character.js
Labels: missing core feature, wish

#44 Monster type, mount gear calculation
  lang/en.json
  model/monster.html
  model/tab/gear-monster.html
  script/hooks/handlebars.js
  script/sheet/actor.js
  script/sheet/character.js
  script/sheet/monster.js
  style/common.css
  style/monster.css
  style/tab/monster-gear.css
  template.json
Labels: enhancement, wish
