Repository fvtt-fria-ligan/forbidden-lands-foundry-vtt, pull requests merged in 2021-03, with the labels that each got.

#47 Add weapon features' toggles and integrate features with chat and combat actions
  chat/item.html
  lang/en.json
  lang/fr.json
  model/raw-material.html
  model/tab/combat.html
  model/tab/gear/armor-main.html
  model/tab/gear/gear-main.html
  model/tab/gear/weapon-main.html
  script/hooks/handlebars.js
  script/hooks/migration.js
  script/sheet/actor.js
  script/sheet/item.js
  style/common.css
  style/item.css
  template.json
Labels: enhancement

#36 Optional Skulls UX.
  model/armor.html
  model/character.html
  model/gear.html
  model/tab/main.html
  model/weapon.html
  script/hooks/migration.js
  script/init.js
  script/sheet/actor.js
  script/sheet/item.js
  style/common.css
Labels: help wanted, wish

#56 Add missing french translations
  lang/fr.json
Labels: localization

#55 Display all weapon features in character sheet
  model/tab/combat.html
Labels: bug

#57 5.0.0 Release Fixes
  .gitignore
  .prettierrc.yml
  lang/en.json
  lang/zh_TW.json
  model/armor.html
  model/building.html
  model/character.html
  model/critical-injury.html
  model/gear.html
  model/hireling.html
  model/monster-talent.html
  model/monster.html
  model/partial/roll-modifiers.html
  model/stronghold.html
  model/tab/gear/gear-artifact.html
  model/tab/gear/gear-main.html
  model/tab/gear/weapon-main.html
  model/tab/hireling-stronghold.html
  model/tab/main.html
  model/talent.html
  model/weapon.html
  script/init.js
  script/sheet/actor.js
  script/sheet/character.js
  script/sheet/item.js
  script/sheet/monster.js
  style/character.css
  style/common.css
  style/item.css
  style/monster.css
  style/stronghold.css
  style/tab/main.css
  system.json
Labels: bug, enhancement, localization

#60 Update zh-TW.json
  lang/zh-TW.json
Labels: localization
