Repository fvtt-fria-ligan/forbidden-lands-foundry-vtt, pull requests merged in 2021-04, with the labels that each got.

#62 Module Reorganization and Refactoring
  CONTRIBUTING.md
  gulpfile.js
  package-lock.json
  src/module/components/dice.js
  src/module/components/roll-dialog.js
  src/module/forbidden-lands.js
  src/module/hooks/dice.js
  src/module/hooks/sheets.js
  src/module/sheets/actor/actor.js
  src/module/sheets/actor/character.js
  src/module/sheets/actor/monster.js
  src/module/sheets/actor/stronghold.js
  src/module/sheets/item/armor.js
  src/module/sheets/item/building.js
  src/module/sheets/item/critical-injury.js
  src/module/sheets/item/gear.js
  src/module/sheets/item/hireling.js
  src/module/sheets/item/item.js
  src/module/sheets/item/monster-attack.js
  src/module/sheets/item/monster-talent.js
  src/module/sheets/item/raw-material.js
  src/module/sheets/item/spell.js
  src/module/sheets/item/talent.js
  src/module/sheets/item/weapon.js
  src/module/system/config.js
  src/module/system/entities.js
  static/assets/border-small.png
Labels: meta

#64 Party Sheet Module integration
  package-lock.json
  src/lang/cs.json
  src/lang/en.json
  src/lang/ru.json
  src/lang/zh-TW.json
  src/party-sheet/.gitignore
  src/party-sheet/LICENSE
  src/party-sheet/README.md
  src/party-sheet/module.json
  src/party-sheet/scripts/dialog/character-picker-dialog.js
  src/party-sheet/scripts/dialog/info-dialog.js
  src/party-sheet/scripts/handlebars.js
  src/party-sheet/scripts/helpers.js
  src/party-sheet/scripts/hooks.js
  src/party-sheet/scripts/party-sheet.js
  src/party-sheet/scripts/travel-actions.js
  src/party-sheet/styles/party-sheet.css
  src/party-sheet/templates/partial/party-member.html
  src/party-sheet/templates/partial/travel-action.html
  src/party-sheet/templates/party.html
  src/party-sheet/templates/tab/main.html
  src/party-sheet/templates/tab/travel.html
Labels: feature, help wanted

#66 Working implementation of Party Sheet
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  src/lang/en.json
  src/module/components/character-picker-dialog.js
  src/module/components/info-dialog.js
  src/module/components/travel-actions.js
  src/module/forbidden-lands.js
  src/module/hooks/handlebars.js
  src/module/hooks/sheets.js
  src/module/sheets/actor/actor.js
  src/module/sheets/actor/party-sheet.js
  src/module/system/entities.js
  src/module/utils/helpers.js
  src/party-sheet/.gitignore
  src/party-sheet/LICENSE
  src/party-sheet/README.md
  src/party-sheet/module.json
  src/party-sheet/scripts/dialog/character-picker-dialog.js
  src/party-sheet/scripts/dialog/info-dialog.js
  src/party-sheet/scripts/handlebars.js
  src/party-sheet/scripts/helpers.js
  src/party-sheet/scripts/hooks.js
  src/party-sheet/scripts/party-sheet.js
  src/party-sheet/scripts/travel-actions.js
  src/party-sheet/templates/partial/party-member.html
  src/party-sheet/templates/partial/travel-action.html
  src/party-sheet/templates/party.html
  src/party-sheet/templates/tab/main.html
  src/party-sheet/templates/tab/travel.html
  src/styles/sheets/_index.scss
  src/styles/sheets/_party-sheet.scss
  src/templates/partial/party-member.hbs
  src/templates/partial/travel-action.hbs
  src/templates/party.hbs
  src/templates/tab/party-main.hbs
  src/templates/tab/travel.hbs
  static/template.json
Labels: feature

#69 ✨ Push Roll on Chat Cards: Merge pull request #62 from aMediocreDad/dev
  src/module/components/dice-roller.js
  src/module/forbidden-lands.js
  src/module/sheets/actor/character.js
  src/templates/chat/roll.hbs
Labels: feature

#77 chore(editorconfig): Added new rule for scss in editorconfig
  .editorconfig
  .prettierrc.json
Labels: meta

#73 Character Generator as is
  gulpfile.js
  src/lang/en.json
  src/module/components/character-generator/character-converter.js
  src/module/components/character-generator/character-generator.js
  src/module/forbidden-lands.js
  src/module/hooks/handlebars.js
  src/module/sheets/actor/character.js
  src/module/system/settings.js
  src/styles/components/_character-generator.scss
  src/styles/components/_index.scss
  src/styles/system/_foundry-overrides.scss
  src/styles/system/_index.scss
  src/templates/character-generator.hbs
  src/templates/partial/list.hbs
  static/system.json
Labels: feature, qol

#78 🐛 Added missing static files.
  .husky/post-merge
  static/assets/dataset.json
  static/assets/rolling-dices.png
  static/scripts/settings-extender.js
Labels: bug

#82 feat: ✨ Item Quantities added to Stronghold Sheet.
  src/lang/en.json
  src/module/sheets/actor/actor.js
  src/module/sheets/actor/stronghold.js
  src/module/system/config.js
  src/styles/sheets/tab/_gear.scss
  src/styles/sheets/tab/_monster-gear.scss
  src/styles/sheets/tab/_stronghold-gear.scss
  src/templates/raw-material.hbs
  src/templates/tab/gear-character.hbs
  src/templates/tab/gear-monster.hbs
  src/templates/tab/gear-stronghold.hbs
  src/templates/tab/gear/gear-supply.hbs
  static/template.json
Labels: feature

#80 ✨ Moved styling from official content modules to system.
  .gitignore
  src/styles/components/_chat.scss
  src/styles/sheets/_character.scss
  src/styles/sheets/_item.scss
  src/styles/sheets/_monster.scss
  src/styles/sheets/_stronghold.scss
  src/styles/sheets/tab/_main.scss
  src/styles/system/_fonts.scss
  src/styles/system/_foundry-overrides.scss
  src/styles/system/_main.scss
  src/styles/system/_root.scss
  static/assets/fbl-sun.webp
  static/assets/journal-art/box-border-large.webp
  static/assets/journal-art/small-border.webp
  static/assets/journal-art/title-border.webp
  static/fonts/IM_FELL_DW_Pica_Roman.ttf
  static/fonts/IM_FELL_Double_Pica_Roman.ttf
  static/fonts/IM_FELL_Great_Primer_Italic.ttf
  static/fonts/IM_FELL_Great_Primer_Roman.ttf
  static/fonts/IM_FELL_THREE_LINE_PICA.ttf
  static/fonts/Swordlings.ttf
  static/fonts/skullz.ttf
Labels: bug, feature, qol

#84 feat(character generator): style for new feature
  src/styles/components/_character-generator.scss
  src/styles/system/_main.scss
  src/templates/character-generator.hbs
  src/templates/partial/list.hbs
Labels: feature, qol

#90 build: 📦️ Extensive changes to the build process
  .github/workflows/release.yml
  .gitignore
  .husky/post-merge
  .husky/pre-commit
  .prettierignore
  gulpfile.js
  package-lock.json
  package.json
  rollup.config.js
Labels: meta

#88 Update pt-br.json
  src/lang/pt-br.json
Labels: localization

#94 🐛 Several fixes to sheets
  src/module/system/entities.js
  src/styles/components/_character-generator.scss
  src/styles/system/_main.scss
  src/templates/party.hbs
Labels: bug

#96 Update pt-br.json
  src/lang/pt-br.json
Labels: localization

#107 🚀 Release ready for 5.2.0
  CONTRIBUTING.md
  gulpfile.js
  package-lock.json
  package.json
  rollup.config.js
  src/lang/en.json
  src/module/components/character-generator/character-converter.js
  src/module/components/character-generator/character-generator.js
  src/module/forbidden-lands.js
  src/module/hooks/calendar-weather.js
  src/module/hooks/migration.js
  src/module/sheets/actor/actor.js
  src/module/sheets/actor/character.js
  src/module/sheets/item/item.js
  src/module/system/settings.js
  src/styles/components/_editor-override.scss
  src/styles/components/_index.scss
  src/styles/sheets/_character.scss
  src/styles/sheets/_item.scss
  src/styles/sheets/_monster.scss
  src/styles/system/_fonts.scss
  src/styles/system/_foundry-overrides.scss
  src/styles/system/_main.scss
  src/styles/utils/_functions.scss
  src/styles/utils/_index.scss
  src/templates/armor.hbs
  src/templates/character-generator.hbs
  src/templates/gear.hbs
  src/templates/limited-character.hbs
  src/templates/monster.hbs
  src/templates/weapon.hbs
  static/LICENSE
  static/assets/dataset.json
  static/fonts/IMFeDPit29C.otf
  static/fonts/IMFeDPrm29C.otf
  static/fonts/IMFeGPit29C.otf
  static/fonts/IMFeGPrm29C.otf
  static/fonts/IMFeTLrm29C.otf
  static/fonts/IMFellDWPica-Italic.ttf
  static/fonts/IMFellDWPica-Regular.ttf
  static/fonts/IMFellGreatPrimer-Italic.ttf
  static/fonts/IMFellGreatPrimer-Regular.ttf
  static/fonts/IM_FELL_THREE_LINE_PICA.ttf
Labels: Release
