Repository fvtt-fria-ligan/forbidden-lands-foundry-vtt, pull requests merged in 2022-03, with the labels that each got.

#188 ✨ distinguishes gear bonus from skill bonus dice
  .gitignore
  src/actor/actor-sheet.js
  src/components/modifiers-component.hbs
  src/components/roll-engine/engine.js
  src/components/roll-engine/templates/dialog.hbs
  src/components/roll-engine/templates/infos.hbs
  src/item/item-document.js
  src/legacy-styles/sheets/_item.scss
  src/legacy-styles/system/_main.scss
  src/system/core/handlebars.js
  src/utils/safe-parse.js
  static/lang/en.json
Labels: feature

#201 :bug: Resolve Bio Tab not scrollable #200
  src/legacy-styles/sheets/tab/_bio.scss
Labels: fix

#203 🔗 Clean up dependencies
  .env
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .husky/post-merge
  .nvmrc
  gulpfile.js
  jsconfig.json
  package.json
  patches/fs-extra-plus+0.6.0.patch
  pnpm-lock.yaml
Labels: CI

#204 📦️ Update PR Check Workflow
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .husky/pre-commit
Labels: CI

#206 :sparkles: Improve Rest button
  src/actor/actor-document.js
  src/actor/character/character-sheet.js
  src/system/core/config.js
  static/lang/en.json
Labels: feature

#208 :sparkles: Improve rest button more
  src/actor/actor-document.js
  src/actor/character/character-sheet.js
  static/lang/en.json
Labels: feature

#209 ✨ Max Initiative Setting
  src/forbidden-lands.js
  src/system/core/combat.js
  src/system/core/config.js
  src/system/core/settings.js
  static/lang/en.json
Labels: feature

#210 Fix #207: Hidden Fields display in chat
  src/components/item-chatcard.hbs
  src/item/item-document.js
Labels: fix

#213 :bug: Monster attacks failed to roll
  src/actor/actor-document.js
  src/actor/monster/monster-sheet.js
Labels: fix
