Repository fvtt-fria-ligan/forbidden-lands-foundry-vtt, pull requests merged in 2022-02, with the labels that each got.

#186 fix: change the translation of damage type in monster attacks
  static/lang/pt-br.json
Labels: fix

#185 fix: change the color of monster attack die
  src/actor/monster/monster-sheet.js
Labels: fix

#190 ✨ Combat Tracker: Resolves #99 and resolves #16
  src/forbidden-lands.js
  src/system/core/combat.js
  static/lang/en.json
Labels: feature

#191 ✨ Adventure Site Sheet
  jsconfig.json
  rollup.config.js
  src/forbidden-lands.js
  src/forbidden-lands.scss
  src/journal/adventure-sites/adventure-site-generator.js
  src/journal/adventure-sites/adventure-site-sheet.js
  src/journal/adventure-sites/styles/index.scss
  src/journal/adventure-sites/templates/adventure-site-sheet.hbs
  src/journal/journal-document.js
  src/legacy-styles/components/_editor-override.scss
  src/legacy-styles/system/_foundry-overrides.scss
  src/system/core/config.js
  src/system/core/handlebars.js
  src/system/core/sheets.js
Labels: feature

#192 ✨ Add fast/slow actions to combat tracker
  src/forbidden-lands.js
  src/legacy-styles/system/_foundry-overrides.scss
  src/system/core/combat.js
  src/system/core/templates/combat.hbs
  static/lang/en.json
Labels: feature

#194 :sparkles: Hide/Show field in artifacts
  src/item/_shared-template-tabs/artifact-tab.hbs
  src/item/gear/templates/main-tab.hbs
  src/item/item-sheet.js
  src/legacy-styles/sheets/_item.scss
  static/lang/en.json
Labels: feature

#195 📦 Move to Esbuild
  esbuild.config.js
  gulpfile.js
  jsconfig.json
  package.json
  pnpm-lock.yaml
  rollup.config.js
  src/forbidden-lands.js
  src/legacy-styles/system/_fonts.scss
Labels: meta, CI

#197 :sparkles: Add rest button
  src/actor/actor-document.js
  src/actor/character/character-sheet.js
  src/actor/monster/monster-sheet.js
  src/legacy-styles/system/_foundry-overrides.scss
  static/lang/en.json
Labels: feature

#198 :bug: Fix Journal not possible to duplciate
  esbuild.config.js
  src/journal/journal-document.js
  src/system/core/handlebars.js
  tools/get-template-paths.js
Labels: fix
